<?php

namespace AppBundle\Repository;

/**
 * MovieAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
