<?php

namespace AppBundle\Repository;

/**
 * MovieCommentVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieCommentVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
