<?php

namespace AppBundle\Repository;

/**
 * MovieVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
