<?php

namespace AppBundle\Repository;

/**
 * MovieViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieViewRepository extends \Doctrine\ORM\EntityRepository
{
}
