<?php

namespace AppBundle\Repository;

/**
 * MovieOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
